Panu/urls.py
from django.conf.urls import url, include 
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from social.apps.django_app import urls as socialUrls
from accounts import urls as accUrls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(accUrls, namespace="accounts")),
    url(r'^registro/', include('registro.urls', namespace="registro")),
    url(r'^persona/', include('dueno.urls', namespace="dueño")),
    url('', include(socialUrls, namespace='social')),
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}),
]

accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout
from . import views 

urlpatterns = [
	url(r'^registro/$', views.Registration.as_view(), name="registro"),
	url(r'^profile/$', views.ProfileView.as_view(), name="profile"),
	url(r'^login/$', login, name="login"),
	url(r'^logout/$', logout, name="logout"),
]

dueno/urls.py
from django.conf.urls import url, include
from .views import index_dueno

urlpatterns = [
    url(r'^index$', index_dueno)
]

registro/urls.py
from django.conf.urls import url, include
from .views import index, mascota_view, mascota_list

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', mascota_view, name='mascota_crear'),
    url(r'^lista$', mascota_list, name='mascota_listar'),
]

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	phone = models.CharField(max_length=10, blank=True, null=True)
	age = models.IntegerField(blank=True, null=True)
	residence = models.TextField(blank=True, null=True)
	photo = models.ImageField(upload_to="users/%Y/%m/%d", blank=True)


	class Meta:
		ordering = ('user',)

	def __str__(self):
		return 'Info del dueño {}'.format(self.user.username)

dueno/models.py
from django.db import models

class Persona(models.Model):
	nombre = models.CharField(max_length=150)
	apellido = models.CharField(max_length=100)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=100)
	correo = models.EmailField()
	domicilio = models.TextField()
 
	def __str__(self):
		return '{} {}'.format(self.nombre. self.apellido) 

registro/models.py
from django.db import models
from dueno.models import Persona

class Medicina(models.Model):
	nombre = models.CharField(max_length=100)

	def __str__(self):
		return '{} '.format(self.nombre) 

class Mascota(models.Model):
	nombre = models.CharField(max_length=100)
	sexo = models.CharField(max_length=20)
	edad = models.IntegerField()
	fecha = models.DateField()
	persona = models.ForeignKey(Persona, blank=True, null=True, on_delete=models.CASCADE)
	medicina = models.ManyToManyField(Medicina)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Repeat your password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'email')

	def clean_password2(self):
		ch = self.cleaned_data
		if ch['password'] != ch['password2']:
			raise forms.ValidationError('Passwords do not match')
		return ch['password2']

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('photo', 'age', 'phone', 'residence')

registro/forms.py
from django import forms 
from .models import Mascota

class MascotaForm(forms.ModelForm):
	class Meta:
		model = Mascota
		fields = [
			'nombre',
			'sexo',
			'edad',
			'fecha',
			'persona',
			'medicina',
		]
		labels = {
			'nombre': 'Nombre',
			'sexo': 'Sexo',
			'edad': 'Edad',
			'fecha': 'Fecha',
			'persona': 'Humano',
			'medicina': 'Medicina',
		}
		widgets = {
			'nombre': forms.TextInput(),
			'sexo': forms.TextInput(),
			'edad': forms.TextInput(),
			'fecha': forms.TextInput(),
			'persona': forms.Select(),
			'medicina': forms.CheckboxSelectMultiple(),
		}

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required 
from .models import Profile
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm

# Create your views here.
class Registration(View):
	def get(self, request):
		template_name = "accounts/registration.html"
		form = UserRegistrationForm()
		context = {
		'form':form,
		}
		return render(request,template_name,context)

	def post(self,request):
		template_name = "accounts/registration.html"
		new_user_form = UserRegistrationForm(request.POST)
		if new_user_form.is_valid():
			new_user = new_user_form.save(commit=False)
			new_user.set_password(new_user_form.cleaned_data['password'])
			# perfil = Profile(instance=new_user)
			new_user.save()
			perfil = Profile()
			perfil.user = new_user
			perfil.save()
			# perfil = Profile.objects.create(user=new_user)
			return redirect('accounts:profile')
		else:
			context = {
			'form':new_user_form
			}
			return render(request,template_name,context)

class ProfileView(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name="accounts/perfil.html"
		userform = UserEditForm(instance=request.user)
		profileform = ProfileEditForm(instance=request.user.profile)
		context = {
		'userform':userform,
		'profileform':profileform,
		}
		return render(request,template_name,context)
	
	def post(self,request):
		template_name="accounts/perfil.html"
		userform = UserEditForm(instance=request.user,data=request.POST)
		profileform = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
		if userform.is_valid() and profileform.is_valid():
			userform.save()
			profileform.save()
			return redirect('accounts:profile')
		else:
			context={
			'userform':userform,
			'profileform':profileform,
			}
			return render(request,template_name,context)

dueno/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index_dueno(request):
	return HttpResponse("Registrate humano!")

registro/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import MascotaForm
from .models import Mascota 

def index(request):
	return render(request, 'index.html')

def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('registro:index')
	else:
		form = MascotaForm()

	return render(request, 'mascota_form.html', {'form':form}) 

def mascota_list(request):
	mascota = Mascota.objects.all()
	contexto = {'mascotas':mascota}
	return render(request, 'mascota_list.html', contexto)

accounts/templates/accounts/perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Perfil</title>
</head>
<body>
	<h1>¡Hola y Bienvenido {{request.user.username}}! </h1>
	<form action="." method="post" accept-charset="utf-8">
		{%csrf_token%}
		{{userform.as_p}}
		{{profileform.as_p}}
		<input type="submit" name="save" value="Guardar">
	</form>

	<h4>¿Quieres cerrar Sesioón?</h5>
	<a href="{%url 'accounts:logout'%}">
		<button type="">
			Hazlo Aquí
		</button>
	</a>
</body>
</html>

accounts/templates/accounts/registration.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Registro</title>
</head>
<body>
	<h1>Registrate</h1>
	<form action="." method="post">
		{%csrf_token%}
		{{form.as_p}}
		<input type="submit" value="Crear usuario">
	</form>
</body>
</html>

registro/templates/index.html
{%extends 'base.html'%}

registro/templates/mascota_form.html
{% extends 'base.html' %}

{%block content%}
<form method="post">
	{%csrf_token%}
	{{form.as_p}}
	<button type="submit">Guardar</button>
</form>

{%endblock%}

registro/templates/mascota_list.html
{% extends 'base.html' %}
{%block content%}
<table class="table table-bordered">
	<thead>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		{%if mascotas%}
		{%for mascota in mascotas %}
		<tr>
			<td>{{mascota.id}}</td>
			<td>{{mascota.nombre}}</td>
			<td>{{mascota.sexo}}</td>
			<td>{{mascota.edad}}</td>
			<td>{{mascota.fecha}}</td>
			<td>{{mascota.persona.nombre}} {{mascota.persona.apellido}}</td>
		</tr>
		{%endfor%}
		{%else%}
		<h1>No hay registros, papud</h1>
		{%endif%}
	</tbody>
</table>
{%endblock%}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static 'css/bulma.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
	<title>{% block title %}Panu - Mascota{% endblock %}</title>
</head>
<body>
{%block header %}
<nav class="nav">
  <div class="nav-left">
    <a class="nav-item is-brand" href="#">
      <img src="/images/panu_logo.png" alt="Panu">
    </a>
  </div>

  <div class="nav-center">
    <a class="nav-item" href="www.facebook.com/Panu">
      <span class="icon">
        <i class="fa fa-facebook"></i>
      </span>
    </a>
    <a class="nav-item" href="www.twitter.com/Panu">
      <span class="icon">
        <i class="fa fa-twitter"></i>
      </span>
    </a>
  </div>

  <span id="nav-toggle" class="nav-toggle">
    <span></span>
    <span></span>
    <span></span>
  </span>

  <div id="nav-menu" class="nav-right nav-menu">
    <a class="nav-item " href="/">
      Registro
    </a>
    <a class="is-hidden nav-item  " href="/templates/">
      <span>Templates</span>
      <span class="tag is-small is-success">New!</span>
    </a>
    <a class="nav-item  is-active" href="/documentation/overview/start/">
      Perfil
    </a>
    <a class="nav-item " href="/blog/">
      Blog
    </a>

    <span class="nav-item">
      <a class="button" >
        <span class="icon">
          <i class="fa fa-twitter"></i>
        </span>
        <span>Tuit Papud</span>
      </a>
  </div>
</nav>
{%endblock%}

{%block content%}
<section class="hero is-info is-large">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        Cuidamos a tu mascota como tú lo harías
      </h1>
      <h2 class="subtitle">
        (O mejor, jajaja nocierto)
      </h2>
    </div>
  </div>
</section>
<section class="section">
    <div class="container has-text-centered">
        <h1 class="title">¡Registrate ahora!</h1>
        <h2 class="subtitle">
          Al obtener una cuenta <strong>Panu</strong>, podrás llevar un mejor control sobre las necesidades de tu mascota
        </h2>
    </div>
</section>
{%endblock%}

{%block footer%}
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>Panu</strong> por <a href="https://github.com/ozobear/Panu">Hugo Cruz // Oscar Godoy</a>. Gracias a BlisS por enseñarnos todo esto y a 
        <a href="https://www.fixter.camp/">FixterGeek</a>. 
      </p>
      <p>
    </div>
  </div>
</footer>
{%endblock%}

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bulma.js' %}"></script>
</body>
</html>